version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      # Persist database data on the host machine
      - ./mysql-data:/var/lib/mysql
      # Initialize database schema and seed data
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Map host port to container port
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    environment:
      APP_PORT: ${APP_PORT}
      # Set to container name 'db' for Dockerized environments
      MYSQL_HOST: db
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      # Configurable profile (dev, test, or prod by .env)
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    working_dir: /app
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
