version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql # Persist database data
      - ./sql-scripts:/docker-entrypoint-initdb.d # Initialize database with SQL scripts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}" # Map host port to container port
    depends_on:
      - db
    environment:
      MYSQL_HOST: db # Set to container name 'db' for Dockerized environments
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE} # Configurable profile (dev, test, or prod by .env)
    working_dir: /app
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
